#!/bin/bash

# NOTES:
# This script is for prepare machine with ssh key permiting ssh connection.
set -euo pipefail

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PUB_KEY_PATH="${SCRIPT_PATH}/keys/key-vm.pub"

## If you want optimize this script write a for in bash for that #
ssh-keygen -R 192.168.1.200
ssh-keygen -R 192.168.1.201
ssh-keygen -R 192.168.1.202
ssh-keygen -R 192.168.1.203
ssh-keygen -R 192.168.1.204
ssh-keygen -R 192.168.1.205
ssh-keygen -R 192.168.1.206

ssh-copy-id -i "$PUB_KEY_PATH" -o StrictHostKeyChecking=no vagrant@192.168.1.200
ssh-copy-id -i "$PUB_KEY_PATH" -o StrictHostKeyChecking=no vagrant@192.168.1.201
ssh-copy-id -i "$PUB_KEY_PATH" -o StrictHostKeyChecking=no vagrant@192.168.1.202
ssh-copy-id -i "$PUB_KEY_PATH" -o StrictHostKeyChecking=no vagrant@192.168.1.203
ssh-copy-id -i "$PUB_KEY_PATH" -o StrictHostKeyChecking=no vagrant@192.168.1.204
ssh-copy-id -i "$PUB_KEY_PATH" -o StrictHostKeyChecking=no vagrant@192.168.1.205
ssh-copy-id -i "$PUB_KEY_PATH" -o StrictHostKeyChecking=no vagrant@192.168.1.206

./init-nodes