#update system packages#
- name: Update system packages Debian/Ubuntu
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Update packages on RHEL/Rocky/Alma
  dnf:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

#install common packages#
- name: Packages Install on Debian/Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
    autoclean: yes
  loop: "{{ deb_applications }}"
  when: ansible_os_family == "Debian"

- name: Update system packages RHEL/CentOS
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ rpm_applications }}"
  when: ansible_os_family == "RedHat"
