- block:
    - name: "Brave-browser | Download keyring and sources"
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - { url: "https://brave-browser-apt-beta.s3.brave.com/brave-browser-beta-archive-keyring.gpg",
            dest: "/usr/share/keyrings/brave-browser-beta-archive-keyring.gpg" }
        - { url: "https://brave-browser-apt-beta.s3.brave.com/brave-browser.sources",
            dest: "/etc/apt/sources.list.d/brave-browser-beta.sources" }
    - name: "Brave-browser | Update and install repos with new brave source"
      ansible.builtin.apt:
        name: brave-browser-beta
        update_cache: true
        state: latest
  when: ansible_os_family == "Debian"
  tags: [brave]
- block:
    # 1) Allow to current user don't ask for password for root
    - name: "Sudoers | pacman sin password para el usuario actual"
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ale
        content: "ale ALL=(ALL) NOPASSWD: /usr/bin/pacman\n"
        mode: "0440"
        validate: "visudo -cf %s"
      become: true
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
  when: ansible_os_family == "Archlinux"
- block:
    - name: "Brave-browser | Check if is install"
      ansible.builtin.stat:
        path: /usr/bin/brave
      register: bravebin
      #debug for output test#
    - name: Debug
      ansible.builtin.debug:
        msg: "Exist"
      when: bravebin.stat.islnk is defined
    - name: Debug
      ansible.builtin.debug:
        msg: "Not Exist"
      when: bravebin.stat.islnk is not defined
    - name: Debug Exist
      ansible.builtin.debug:
        msg: "Exist double"
      when: bravebin.stat.exists
      #debug for output test#
    - name: "Brave-browser | Install with AUR helper 'yay'"
      ansible.builtin.command: yay -S --noconfirm --needed brave-bin
      become: false
  when: 
   - ansible_os_family == "Archlinux" 
   - bravebin.stat.islnk is not defined
