- name: Install fluxcd on windows
  win_chocolatey:
    name: flux
    version: "{{ worksapps.fluxcliversion }}"
    state: present
  when: ansible_system == "Win32NT"

- name: Install fluxcd on macOS
  community.general.homebrew:
    name: fluxcd/tap/flux
  when: ansible_system == "Darwin"

- block:
    - name: "Fluxcd-CLI | Get installation path with command"
      ansible.builtin.shell: command -v flux
      failed_when: false
      changed_when: false
      register: fluxcdcmd
    - name: "Fluxcd-CLI | Check if is install"
      ansible.builtin.stat:
        path: "{{ fluxcdcmd.stdout }}"
      register: fluxcdbin

- block:
    - name: Download fluxcd for Linux and save in /tmp
      ansible.builtin.get_url:
        url: "https://fluxcd.io/install.sh"
        dest: /tmp/install.sh
        mode: '0755'
      when: ansible_system == "Linux"
    - name: Install fluxcd on linux using bash
      ansible.builtin.shell: | 
        FLUX_VERSION={{ worksapps.fluxcliversion }} /tmp/install.sh
      args:
        creates: /usr/local/bin/flux
      when: ansible_system == "Linux"
  when: not (fluxcdbin.stat.exists | default(false))

