- name: Fetch kubectl sha256 checksum
  ansible.builtin.uri:
    url: "https://dl.k8s.io/release/{{ worksapps.k8svers }}/bin/linux/{{ computer_arch }}/kubectl.sha256"
    follow_redirects: all
    return_content: true
  register: kubectl_sha256

- name: Install kubectl client api for kubernetes
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ worksapps.k8svers }}/bin/linux/{{ computer_arch }}/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
    checksum: "sha256:{{ kubectl_sha256.content | trim }}"
